#!/bin/sh
## Environtment
export PATH="${PATH}:$HOME/.dwm/bin"
export _JAVA_AWT_WM_NONREPARENTING=1

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors
#feh --bg-fill ~/Pictures/wall/chad.png &
nitrogen --restore
#if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
#fi

## Start Compositing Manager
#exec ~/.dwm/bin/dwm-compositor &

## Notification Daemon
#if [[ ! `pidof dunst` ]]; then
	
dunst \
-geom "280x50-10+42" -frame_width "1" -font "Iosevka Custom 9" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &

#fi

## Enable power management
#if [[ ! `pidof xfce4-power-manager` ]]; then
	xfce4-power-manager &
#fi


#xrdb merge ~/Public/xresources/ocean/.Xresources &
xsettingsd &
xsetroot -cursor_name left_ptr
exec mpd &
#picom & 

xbacklight -set 100 &
#dwm-bar &
~/.dwm/bars/dracula.sh &
dwm-compositor &
dwm
